deploy-tools/infra/conf/group_vars/all.yml
deploy-tools/infra/deploy-kqi-infra.sh
deploy-tools/kamonohashi/deploy-kqi.sh

kubecpray 2.8.xではcoreDNSが大量に立つので、バージョンアップして回避する

各種インフラ コンポーネントのバージョンアップ

---

web-pages/src/components/system-setting/user/TenantRoleSelector.vue

ユーザ管理画面のテナントロール設定部の表示を修正しました。
- チェックボックスからラジオボタンに変更
- レイアウト一部修正
ご確認をお願いします。

テナントロール設定部の表示を修正

---

web-api/platypus/platypus/Logic/ClusterManagementLogic.cs

前処理実行時、テナントが使用できるノードがない場合のエラー処理を追加しました。
ご確認をお願いします。

前処理実行時、使用できるノードがない場合のエラー追加

---

web-pages/src/components/common/SmartSearchInput/InputDate.vue

検索時、10000年以上の日付を指定すると正しく検索されなかったため、
最大日付を指定するように修正しました。
ご確認をお願いします。

10000年以上の検索時、最大日付を指定するように修正

---

web-pages/src/components/inference/Create.vue

推論管理の[マウントする学習]を選択時の動作を修正しました。
修正内容としては、
学習管理の親学習選択時の動作と同様、選択した学習の内容を反映しないようにしました。
#67 に関連した修正です。ご確認をお願いします。

推論管理の[マウントする学習]を選択時の動作を修正

---

web-api/platypus/platypus/ApiModels/ResourceApiModels/NodeResourceOutputModel.cs
web-api/platypus/platypus/ApiModels/ResourceApiModels/TenantResourceOutputModel.cs
web-api/platypus/platypus/Infrastructure/Util.cs
web-pages/src/components/system-setting/cluster-resource/Edit.vue

リソース管理画面の以下の表示を修正しました。
- ノードが振り分けられていないときのログのファイル名
- CPUとメモリの合計値の計算方法
ご確認をお願いします。

リソース管理画面の表示を修正

---

cli/kamonohashi/cli/training.py
web-api/platypus/platypus/ApiModels/TrainingApiModels/AttachedFileOutputModel.cs

#105 の要望に応え、より汎用的な仕様になるよう
学習のdownload-filesコマンドを修正しました。
- オプションとして、ファイルIDを追加（複数指定可能）
指定なしの場合、すべてのファイルをダウンロードする
ご確認をお願いします。

CLIの学習のdownload-filesコマンドを修正

---

web-api/platypus/platypus/Controllers/spa/DataController.cs

#151 に関して、対応が完了いたしました。
データ名の前後の空白文字を登録時に除去するように修正しました。
ご確認をお願いします。

データ名の前後の空白文字を登録時に除去

---

web-api/platypus/platypus/Logic/InferenceLogic.cs
web-api/platypus/platypus/Logic/PreprocessLogic.cs
web-api/platypus/platypus/Logic/TrainingLogic.cs

#92 に関して、対応が完了いたしました。
コンテナ削除処理に時間がかかるため、
ステータス更新処理とコンテナ削除処理のタイミング（順番）を修正しました。
また、web-api/platypus/platypus/Logic/Interfaces/InferenceLogic.csのファイルの階層に誤りがあったため、
web-api/platypus/platypus/Logic/InferenceLogic.csに移動しました。
ご確認をお願いします。

ステータス更新とコンテナ削除のタイミングを修正

---

web-pages/src/components/data/Index.vue
web-pages/src/components/data/TagEditor.vue
web-pages/src/components/dataset/DatasetTransfer/DataList.vue

#131 に関して、対応が完了いたしました。
データ管理で長い文字列のタグを設定した場合レイアウト崩れが発生するため、省略表示するように修正いたしました。
ご確認をお願いします。

データのタグの省略表示対応

---

web-pages/src/components/inference/Index.vue
web-pages/src/components/training/Index.vue

#130 に関して、対応が完了いたしました。
学習管理・推論管理の一覧画面にて、実行コマンド列のスタイルを修正しました。
- コマンドが長い場合、表示領域が縦に長くなるので、3行まで表示
ご確認をお願いします。

学習・推論の一覧の実行コマンド列のスタイルを修正

---

web-api/platypus/platypus/Controllers/spa/AccountController.cs
web-api/platypus/platypus/Controllers/spa/UserController.cs

#153 に関して、対応いたしました。
apiでユーザ名の前後の空白文字を除去する処理を追加しました。
ご確認をお願いします。

ユーザ名の前後の空白は除く処理を追加

---

web-api/platypus/platypus/Controllers/spa/DataSetController.cs
web-api/platypus/platypus/DataAccess/Repositories/Interfaces/TenantRepositories/IDataSetRepository.cs
web-api/platypus/platypus/DataAccess/Repositories/TenantRepositories/DataSetRepository.cs
web-api/platypus/platypus/Logic/DataLogic.cs
web-api/platypus/platypus/Logic/Interfaces/IDataLogic.cs

#146 に関して、修正対応が完了いたしました。
DataSetController.GetDataFiles内のdataLogic.GetDataFilesの処理に時間がかかっているため、Time Outが発生していました。
そのため、ダウンロード取得を並列処理する修正を行いました。
ご確認をお願いします。

データセットのダウンロード処理の修正（ダウンロードURL取得を並列化）

---

web-pages/package-lock.json
web-pages/package.json

「-webkit-box-orient」がビルド時に消えてしまうので、autoprefixerをアップグレードしました。
参考）https://qiita.com/watanabejunya/items/40b6c915639be5fa943f

autoprefixerのアップグレード

---

cli/kamonohashi/cli/data.py
web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/common_scripts.yaml
web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/preproc_scripts.yaml

#48 に関して対応いたしました。
前処理、学習、推論実行時にデータのメタ情報(jsonファイル)を取得するように修正いたしました。
それに伴い、データ管理の以下のCLIコマンドを修正しました。
Optionsに'-d'を追加しました。'dataset get'と使用方法は同様です。
```
kqi data get (ID) [Options]
```
ご確認をお願いします。

ジョブ実行時にデータのメタ情報を取得するように修正

---

web-pages/src/components/system-setting/node/Create.vue

#174 に関して対応いたしました。
ノード登録画面の表示時に、デフォルトとして'Public'が設定されるように修正しました。
ご確認をお願いします。

ノード登録画面のアクセスレベルのデフォルト値設定

---

web-pages/src/components/inference/Index.vue
web-pages/src/components/training/Index.vue

#130 について、追加で対応が完了いたしました。
以下のスタイルがビルド時に削除されてしまい、行数指定が正しく動作しなかったため、修正しました。
```
-webkit-box-orient: vertical;
```
ご確認をお願いします。
確認項目としては、ビルドした際に生成されるcssファイルに
該当のスタイルが記載されているかを確認ください。
メモ）
ビルドは以下のコマンドを実行してください。
```
npm run build
```

[-webkit-box-orient]がビルド時に除かれないように修正

---

web-pages/src/components/training/Index.vue

#118 に関して対応いたしました。
学習管理の一覧画面に一括削除機能を追加しました。
削除したい学習履歴のチェックボックスにチェックを入れ、一括削除ボタンを押下することで削除できます。
ご確認をお願いします。

学習一覧画面に一括削除機能を追加

---

web-pages/src/components/dataset/DatasetTransfer/DataList.vue

#121 に関して対応いたしました。
データセット作成・編集画面にて、データ一覧の表示部に合計ページ数を表示するようにしました。
ご確認をお願いします。

データセット管理のデータ一覧に合計ページ数を表示

---

web-api/platypus/platypus/DataAccess/Repositories/Interfaces/TenantRepositories/INotebookHistoryRepository.cs
web-api/platypus/platypus/DataAccess/Repositories/TenantRepositories/NotebookHistoryRepository.cs
web-api/platypus/platypus/Logic/HostedService/DeleteNotebookContainerTimer.cs

#216 に関して、対応いたしました。
一回取得した結果がキャッシュされて（残ってしまって）いるため、再度取得しようとしても更新されない。
そのため、キャッシュされないように修正しました。
ご確認をお願いします。

NotebookHistoriesの実行中レコード検索をキャッシュされないように修正

---

web-api/platypus/platypus/Infrastructure/Types/GitServiceType.cs
web-api/platypus/platypus/Logic/GitLogic.cs
web-api/platypus/platypus/Services/GitLabComService.cs
web-api/platypus/platypus/Services/GitLabService.cs
web-api/platypus/platypus/Startup.cs
web-pages/src/components/system-setting/git/Index.vue

#191 に関して対応が完了いたしました。
GitLab.comを登録、使用できるように専用サービスクラスを追加しました。
学習実行画面等のGitのリポジトリについては、一覧の取得は行わずにユーザ自身に手入力させる想定です。
また、
Gitの一覧画面についてですが、
種別を汎用的に取得表示するために修正しております。（レジストリの一覧と同様の処理にしました。）
合わせてご確認をお願いします。

GitLab.comを使用できるようにサービス追加と修正

---

web-pages/src/components/system-setting/git/Create.vue
web-pages/src/components/system-setting/git/Edit.vue
web-pages/src/components/system-setting/registry/Create.vue
web-pages/src/components/system-setting/registry/Edit.vue

#200 に関して対応が完了いたしました。
Git管理の登録、編集画面のUIとレジストリ管理の登録・編集画面のUIを変更しました。
Git管理について。
- [API URL]が非アクティブの場合
　 [リポジトリURL]が変更されたら、[API URL]に反映する。
- [API URL]がアクティブの場合
　[API URL]を任意に変更可能。
レジストリ管理について。
- [API URL]が非アクティブの場合
　[ホスト名]が変更されたら、[API URL]に反映する。
- [API URL]がアクティブの場合
　[API URL]を任意に変更可能。
- [URL]が非アクティブの場合
　[ポート]または[API URL]が変更されたら、[URL]に反映する。
- [URL]がアクティブの場合
　[URL]を任意に変更可能。
ご確認をお願いします。

GitとRegistryの登録・編集画面のUI変更

---

web-pages/src/components/system-setting/quota/Index.vue

#198 に関して対応いたしました。
クォータ管理画面にて、各テナントごとに使用できるリソース上限の最大値を設定しました。
現状、学習や推論実行時に設定できる上限を参考に設定しました。
- CPU：200
- Memory：200
- GPU：16
ご確認をお願いします。

クォータ管理で最大値を指定

---

web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/inference_scripts.yaml
web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/training_scripts.yaml

もし、zip化に成功した場合、ステータスがcompletedになってしまうため、
実行コマンド失敗時にzip化処理をしないように修正しました。
ご確認をお願いします。

実行コマンド失敗時にzip化しないように修正

---

web-pages/src/components/inference/Edit.vue
web-pages/src/components/training/Edit.vue

#235 に関して、対応いたしました。
学習と推論履歴の結果zip圧縮の表示を変更しました。
変更できない仕様のため、文字列に変更しました。
ご確認をお願いします。

学習・推論履歴の結果zip圧縮の表示を変更

---

web-pages/src/components/dataset/DatasetTransfer/DataList.vue

#201 に関して対応いたしました。
データセット管理のデータ詳細ポップ表示上に、データ編集画面へ遷移するためのボタンを追加しました。
ご確認をお願いします。

データセットからデータ編集画面へ遷移するボタンを追加

---

web-pages/src/util/axios-ext.js

#133 について対応いたしました。
エラーメッセージが見切れることがある原因として、サーバ側の処理で発生したExceptionを長い文字列として画面上に表示していました。
ユーザとしては、システム内部のエラーについて画面に表示されてもFront側からは何もできないので、詳細部('detail')のメッセージは表示しないように修正しました。
ご確認をお願いします。

エラーメッセージの見切れを修正

---

web-api/platypus/platypus/DataAccess/Repositories/GitRepository.cs
web-api/platypus/platypus/DataAccess/Repositories/RegistryRepository.cs
web-api/platypus/platypus/DataAccess/Repositories/UserRepository.cs

#255 に関して対応いたしました。
ユーザ情報更新時にテナントのGit,Registryトークンの情報が空欄のものを参照しないように修正しました。
また、テナント情報更新時にも同様の処理があったため修正しました。
ご確認よろしくお願いします。

ユーザ・テナント情報更新時にトークン情報が消えないよう修正

---

web-api/platypus/platypus/Controllers/spa/DataController.cs

#262 に関して対応いたしました。
データ情報を更新もしくは削除時に未使用のタグがあった場合DBから削除するように修正しました。
ご確認よろしくお願いします。

データ更新・削除時に未使用のタグをDBから削除するように修正

---

web-pages/src/components/inference/Index.vue

#259 に関して対応いたしました。
推論管理の一覧画面に一括削除機能を追加しました。
削除したい推論履歴のチェックボックスにチェックを入れ、一括削除ボタンを押下することで削除できます。
一括削除ボタンはチェックボックスにチェックを入れることで表示されます。
ご確認をお願いします。

推論一覧画面に一括削除機能を追加

---

web-pages/src/components/common/ContainerSelector.vue
web-pages/src/components/common/GitSelector.vue

#265 コピー実行時にGit,Registryのチェックでエラーが出ないよう修正
デフォルトGit,Registry以外を設定している履歴のコピー時、デフォルトの値でチェックを行わないよう修正しました。
ご確認よろしくお願いします。

デフォルトGit,Registry以外を設定している履歴のコピー時、デフォルトの値でチェックを行わないよう修正

---

deploy-tools/infra/roles/gpu-server/tasks/nvidia-docker2.yml

これまではキー登録がすでにある場合に何もしなかったが、
nvidia-docker2のキーが更新された場合に、aptでエラーが出るようになるので
常に上書きするように修正。（参考：https://nvidia.github.io/nvidia-docker/）

nvidia docker2のaptキーを更新するように修正

---

web-pages/src/components/system-setting/user/TenantRoleSelector.vue

#253 ユーザ情報に新規テナントを追加した際にデフォルトでロールが設定される機能を追加しました。
デフォルトとして設定されるロールはロール管理で設定されている表示順の先頭に来るものです。
以上、ご確認よろしくお願いします。

ユーザ情報に新規テナントを追加した際にデフォルトロールを設定する機能を追加

---

web-api/platypus/platypus/Logic/ClusterManagementLogic.cs
web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/notebook_scripts.yaml

#279 の対応
/kqi/outputを初期ディレクトリとし、/kq/git, /kqi/parent, /kqi/inputへのシンボリックリンクを作成。
初期ディレクトリが/kqi/outputの内部となるため、何も意識せずともファイルを作成、保存すると永続化される。ただし、git, parent, input内にファイルを作成すると、永続化されないことに注意(要マニュアル記述)

jupyter labの起動ディレクトリを/kqi/outputに変更

---

web-api/platypus/platypus/Controllers/spa/TrainingController.cs

#298 について、対応いたしました。
マウントする学習の一覧取得のAPIに、ノートブックからのアクセスを許可していないことが原因です。
そのため、APIにノートブックからのアクセスを許可しました。
ご確認をお願いします。

マウントする学習一覧取得APIにNotebookからのアクセスを許可

---

web-api/platypus/platypus/Controllers/spa/PreprocessingController.cs

#300 に関して対応いたしました。
前処理編集画面で保存ボタンを押下した際、入力項目でDB値の書き換えを行い、コミットするまでは正常に処理できています。  
しかし、出力用モデルに格納する際のモデルが正しくありません。そのため、nullの項目を設定しようとしてエラーが発生しています。  
`DetailsOutputModel`を返却モデルにしていたが、`IndexOutputModel`を返却するように修正しました。
ご確認をお願いします。

前処理編集の返却するモデルを変更

---

web-api/platypus/platypus/Logic/ClusterManagementLogic.cs
web-api/platypus/platypus/Migrations/20200319064613_v2.0.0.Designer.cs
web-api/platypus/platypus/Migrations/CommonDbContextModelSnapshot.cs

#327 のコミット漏れです。
SDKに最新APIモデルを反映したことで、CLIから学習実行しようとすると、portListが設定できないので、nullが入ってしまうため、nullチェックを追加しました。
ご確認をお願いします。

学習実行時portListのnullチェックを追加

---

web-pages/src/components/KqiHeader.vue

#357 に関して対応いたしました。
割り当てられたテナント数が11以上の際にスクロールバーを表示するよう修正しました。
ご確認よろしくお願いします。

画面右上のテナント切り替え部分が見切れないよう修正

---

web-pages/src/views/inference/Create.vue
web-pages/src/views/notebook/Create.vue
web-pages/src/views/training/Create.vue

#355 に関して対応いたしました。
コピー実行を行う際にブランチが切り替わらないよう修正しました。
ご確認よろしくお願いします。

コピー実行時ブランチが切り替わるバグの修正

---

web-pages/src/views/preprocessing/HistoryEdit.vue

#350 に関して対応いたしました。
前処理履歴詳細画面に作成したデータのIDを表示、対象のIDをクリックすることでデータ編集画面に遷移する機能を追加しました。
ご確認よろしくお願いします。

前処理履歴詳細画面に作成したデータのID表示、データ編集画面への遷移機能を追加

---

web-pages/src/views/preprocessing/Index.vue

#380 に関して対応いたしました。
前処理実行画面をｘボタンで閉じた後に実行画面を開いてもエラーページに遷移しないよう修正しました。
ご確認よろしくお願いします。

前処理実行画面を閉じた後他の画面が開けなくならないように修正

---

web-pages/src/components/KqiHeader.vue

#384 に関して対応いたしました。
ヘッダー部分のユーザー・テナント名が長い場合省略して表示するように修正しました。
ご確認よろしくお願いします。

ヘッダー部分のユーザー・テナント名が長い場合省略して表示するよう修正

---

web-api/platypus/platypus/Controllers/spa/TrainingController.cs

#382 関して対応いたしました。
開放ポート未指定の学習履歴を閲覧時、serviceへの問い合わせを行わないよう修正しました。
ご確認よろしくお願いします。

開放ポート未指定時、serviceの問い合わせを行わないよう修正

---

web-api/platypus/platypus/Controllers/spa/DataSetController.cs
web-pages/src/views/dataSet/DatasetTransfer/Index.vue

#100 に関して対応いたしました。
データセット編集画面でのデータを全てデータID降順でソートするように修正しました。
ご確認よろしくお願いします。

データセット編集画面でのデータのソートを修正

---

web-api/platypus/platypus/Services/GitBucketService.cs
web-api/platypus/platypus/Services/GitHubService.cs

gitlab登録ではgitlabのapiエンドポイントのパス/api/v4を自動付与しますが、
gitbucketはgithubのコードを流用している関係でgitbucketのapiエンドポイントのパス/api/v3を自動付与されない状態でした

gitbucketのapi url登録時に/api/v3を付けないといけないのをなくす

---

web-api/platypus/platypus/Logic/ClusterManagementLogic.cs

tensorboard2では従来の複数指定方法はlogdir_specというオプションに変更になっていた

tensorboardのバージョンアップで複数比較が動かなくなったのを修正

---

web-pages/src/views/system-setting/quota/Index.vue

アクアリウムの方はシステム設定のメニューを削除するので修正していません

クォータ管理画面の最大値をCPU200→250、メモリ200→500に修正

---

release-tools/build-docker/web-api-Dockerfile

web-api-Dockerfileをdotnet core 3.1に対応するため更新。
以下に関連。
- https://github.com/KAMONOHASHI/kamonohashi/pull/566

web-api-Dockerfileをdotnet core 3.1に対応するため更新

---

release-tools/README.md
release-tools/build-notebook-image/Dockerfile
web-api/platypus/platypus/Controllers/spa/NotebookController.cs
web-pages/src/views/notebook/Create.vue

notebookのデフォルトイメージのバージョンを上げた。[Docker Image (dockerhub)](https://hub.docker.com/layers/kamonohashi/jupyterlab/tensorflow-2.9-pytorch-1.12/images/sha256-69234592e167621e3f49aaec8b87c94d18d59a799512ff8bc3167e6b155b741a?context=explore)
- python 3.8.10
- tensorflow 2.9.0
- pytorch 1.12.0
- jupyterlab 3.4.2

notebook機能のデフォルトイメージの変更
