KAMONOHASHI/kamonohashi

- web-api/platypus/platypus/Controllers/spa/RegistryController.cs
- web-api/platypus/platypus/Services/GitLabRegistryService.cs
- web-pages/src/components/system-setting/registry/Create.vue
- web-pages/src/components/system-setting/registry/Edit.vue
#5 の修正。
コンテナレジストリ機能連携機能を修正し、GitLab11.8以降の利用を可能にしました。
> コンテナレジストリ機能連携機能の修正

- web-api/platypus/platypus/DataAccess/Core/Seed.cs
- web-api/platypus/platypus/DataAccess/Repositories/TenantRepositories/SettingRepository.cs
DB初期化成功時のみ、初期テナントをストレージとクラスタへ同期するように修正しました。
> DB初期化時のストレージとクラスタの同期を修正

- web-api/platypus/platypus/DataAccess/Repositories/Interfaces/TenantRepositories/IPreprocessHistoryRepository.cs
- web-api/platypus/platypus/DataAccess/Repositories/TenantRepositories/PreprocessHistoryRepository.cs
- web-api/platypus/platypus/Logic/PreprocessLogic.cs
#14 に関して、対応が完了いたしました。
ご確認をお願いします。
> 異なるテナントの前処理削除処理を修正

- web-api/platypus/platypus/DataAccess/Repositories/RegistryRepository.cs
> Registryのプロジェクト名表示を修正

- web-pages/src/util/util.js
#19 について、修正が完了いたしました。
ご確認をお願いします。
> ファイルサイズの単位表記を修正

- web-api/platypus/platypus/Controllers/spa/InferenceController.cs
#21 について、対応が完了いたしました。
ご確認をお願いします。
> 推論管理の[マウントした学習]の検索を修正

- web-api/platypus/platypus/Controllers/spa/ResourceController.cs
- web-api/platypus/platypus/DataAccess/Repositories/Interfaces/IUserRepository.cs
- web-api/platypus/platypus/DataAccess/Repositories/UserRepository.cs
#29 に関して、修正が完了いたしました。
ご確認をお願いします。
> リソース管理のユーザ名表示を修正

- web-pages/src/components/common/SmartSearchInput/Index.vue
- web-pages/src/components/data/Edit.vue
- web-pages/src/components/data/Index.vue
- web-pages/src/components/dataset/DatasetTransfer/DataList.vue
- web-pages/src/components/dataset/Edit.vue
- web-pages/src/components/dataset/Index.vue
- web-pages/src/components/inference/FileIndex.vue
- web-pages/src/components/preprocessing/HistoryIndex.vue
- web-pages/src/components/preprocessing/Index.vue
- web-pages/src/components/preprocessing/PreprocessingHistory.vue
- web-pages/src/components/preprocessing/PreprocessingHistoryEdit.vue
- web-pages/src/components/training/FileIndex.vue
表記揺れを修正
- 「日」→「日時」
ご確認をお願いします。
> 表記揺れ修正　「日」→「日時」

- web-pages/src/components/dataset/Index.vue
- web-pages/src/components/inference/Index.vue
- web-pages/src/components/preprocessing/Create.vue
- web-pages/src/components/preprocessing/Index.vue
- web-pages/src/components/system-setting/git/Create.vue
- web-pages/src/components/system-setting/node/Create.vue
- web-pages/src/components/system-setting/registry/Create.vue
- web-pages/src/components/system-setting/role/Index.vue
- web-pages/src/components/system-setting/storage/Create.vue
- web-pages/src/components/system-setting/tenant/Create.vue
- web-pages/src/components/system-setting/user/Create.vue
- web-pages/src/components/system-setting/user/Index.vue
- web-pages/src/components/tenant-manage/role/Index.vue
- web-pages/src/components/training/Index.vue
タイトルとボタンの表記揺れを修正しました。
ご確認をお願いします。
> タイトルとボタンの表記揺れを修正

- web-pages/src/components/system-setting/role/Create.vue
- web-pages/src/components/system-setting/role/Edit.vue
ロール管理の新規作成と編集画面のソート順のレイアウト崩れを修正しました。
ご確認をお願いします。
> ロール管理画面のレイアウト崩れを修正

- web-api/platypus/platypus/Controllers/spa/AccountController.cs
- web-api/platypus/platypus/Controllers/spa/UserController.cs
ローカルユーザのパスワード設定を修正。
- スペースのみの入力内容の場合NGとする
ご確認をお願いします。
> ローカルユーザのパスワード設定を修正

- web-pages/src/components/system-setting/storage/Edit.vue
- web-pages/src/components/system-setting/storage/Index.vue
- web-pages/src/router/index.js
ストレージ管理内の新規登録・編集への画面遷移をvue-routerに記載しました。
ご確認をお願いします。
> ストレージ管理内の画面遷移をvue-routerに記載

- web-api/platypus/platypus/Controllers/spa/ResourceController.cs
#45 に関して、対応が完了いたしました。
ご確認をお願いします。
> テナントリソース管理画面のユーザ名表示を修正

- web-api/platypus/platypus/Infrastructure/ContainerStatus.cs
- web-api/platypus/platypus/ServiceModels/KubernetesModels/GetPodsOutputModel.cs
- web-api/platypus/platypus/Services/KubernetesService.cs
#3 に関して、対応が完了いたしました。
ご確認をお願いします。
> ジョブのステータスOOM Killed表示に対応

- web-pages/src/components/system-setting/menu/Index.vue
#20 に関して、対応が完了いたしました。
ご確認をお願いします。
> メニューアクセス管理画面の表示を修正

- web-api/platypus/platypus/ApiModels/TenantApiModels/CreateInputModel.cs
- web-api/platypus/platypus/Controllers/spa/TenantController.cs
- web-pages/src/components/system-setting/tenant/Create.vue
テナント作成において、必須チェックのメッセージの項目名がわかりづらいため、変更しました。
- 'Name'　→　'TenantName'
ご確認をお願いします。
> テナント名のプロパティ名を変更

- web-api/platypus/platypus/Controllers/spa/StorageController.cs
以下の処理を追加しましたので、ご確認をお願いします。
- ストレージ保存時、対象のストレージを登録しているテナントが存在する場合、バケットを作成する
> ストレージ保存時バケットを作成する処理を追加

- web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/common_scripts.yaml
検証環境にて 自己署名証明書でhttps化したgitlab(v11.11.3) でgit cloneできることを確認しました。
レビューお願いします。
> 自己署名証明書を許容する設定を追記

- deploy-tools/infra/conf/group_vars/all.yml
- deploy-tools/infra/roles/os/tasks/nfs-client.yml
> Fix inconsistent component version

- web-api/platypus/platypus/DataAccess/Repositories/TenantRepositories/SettingRepository.cs
DBの初期化を初回時のみ実行するように修正しました。
ご確認をお願いします。
> DBの初期化を初回時のみ実行するように修正

- web-pages/src/components/common/DatasetSelector.vue
#145 に関して、対応いたしました。
データセットの名称または、メモが長い場合、省略するようにしました。
ご確認をお願いします。
> データセットリストの見切れを修正

- web-pages/src/App.vue
- web-pages/src/components/account/Setting.vue
以下のチケットについて、対応いたしました。
- #81
- #77
ご確認をお願いします。
> 画面レイアウトを修正

- web-api/platypus/platypus/Logic/ClusterManagementLogic.cs
#172 に関して対応いたしました。
TensorBoard用のコンテナを起動する際、
レジストリトークンを取得・設定している処理を削除しました。
ご確認をお願いします。
> TensorBoardを起動する際、レジストリトークンを設定する処理を削除

- web-pages/src/components/account/GitSelector.vue
- web-pages/src/components/account/RegistrySelector.vue
- web-pages/src/components/account/Setting.vue
#108 に関して対応が完了いたしました。
ユーザ情報設定画面のGit TokenとRegistry Tokenの更新時に
成功メッセージが表示されるように修正いたしました。
ご確認をお願いします。
> ユーザ情報設定のGit TokenとRegistry Token更新時、成功メッセージ表示を追加

- web-api/platypus/platypus/Controllers/spa/DataController.cs
DataController.csにて、ファイル取得の重複処理を削除しました。
ご確認をお願いします。
> データ管理にてファイル取得の重複処理を削除

- web-pages/src/api/v1/api.generator.js
ユーザキャンセルすると、Front側でエラーが発生し、ユーザキャンセルできないのを修正しました。
ご確認をお願いします。
> ユーザキャンセルするとfront側でエラーになるのを修正

- web-pages/src/api/v1/api.generator.js
- web-pages/src/api/v1/api.js
> API呼び出しの修正

- web-api/platypus/platypus/platypus.csproj
再度リリースするため、masterから1.1にマージします。
> 1.1.0リリースのためのマージ

- web-api/platypus/platypus/Controllers/spa/NotebookController.cs
> ノートブック管理画面検索の動作不良を修正

- web-api/platypus/platypus/Controllers/spa/TrainingController.cs
- web-pages/src/api/v1/api.js
マウントする学習の一覧が表示されないバグを修正しました。
v1.1.0のデグレになります。
ご確認をお願いします。
> マウントする学習の一覧が表示されないバグを修正

- deploy-tools/deploy-basic-cluster.sh
> Fix hosts deploy bug

- web-api/platypus/platypus/Controllers/spa/ClusterController.cs
- web-api/platypus/platypus/Controllers/spa/DataController.cs
- web-api/platypus/platypus/Controllers/spa/DataSetController.cs
- web-api/platypus/platypus/Controllers/spa/GitController.cs
- web-api/platypus/platypus/Controllers/spa/NodeController.cs
- web-api/platypus/platypus/Controllers/spa/RegistryController.cs
- web-api/platypus/platypus/Controllers/spa/ResourceController.cs
- web-api/platypus/platypus/Controllers/spa/RoleController.cs
- web-api/platypus/platypus/Controllers/spa/StorageController.cs
- web-api/platypus/platypus/Controllers/spa/TenantController.cs
- web-api/platypus/platypus/Controllers/spa/TrainingController.cs
- web-api/platypus/platypus/Controllers/spa/UserController.cs
- web-pages/src/api/v1/api.js
#18 から派生して、以下の対応いたしました。
KAMONOHASHIでは、APIに対して、アクセスを許可するMenuCodeを設定している。
適さないMenuCodeに対して許可している場合があったため整理、修正しました。
ご確認をお願いします。
> apiに対してアクセス許可するメニューコードを整理、修正

- web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/common_scripts.yaml
- web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/inference_scripts.yaml
- web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/notebook_scripts.yaml
- web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/preproc_scripts.yaml
- web-api/platypus/platypus/ServiceModels/KubernetesModels/Templates/ConfigMap/training_scripts.yaml
#74 に関して、対応いたしました。
コンテナ内のデータダウンロード処理に失敗した際、ジョブ自体を停止(Killed)にするようにしました。
ご確認をお願いします。
> コンテナ内のデータダウンロードに失敗した際にジョブを停止

- web-api/platypus/platypus/Controllers/spa/NotebookController.cs
#241 に関して対応いたしました。
TensorBoardOutputModelの実装のように、EndPointOutputModel.Urlに設定する値を
共通のエンドポイントに修正しました。
ご確認をお願いします。
> ノートブックへのアクセス先を共通のエンドポイントに修正

- web-pages/src/components/account/GitSelector.vue
- web-pages/src/components/account/RegistrySelector.vue
> Add show/hide feature for git token and registory token

- web-pages/src/components/system-setting/registry/Index.vue
> Replace access user with project name in registry list

- web-api/platypus/platypus/ApiModels/NotebookApiModels/RerunInputModel.cs
- web-api/platypus/platypus/Controllers/spa/NotebookController.cs
- web-pages/src/components/notebook/Create.vue
#287 に関して対応いたしました。
ノートブックの再起動時にコンテナ情報とモデル情報を変更できるように修正いたしました。
ご確認をお願いします。
> ノートブック再起動の項目にコンテナ情報とモデル情報を追加

- cli/kamonohashi/cli/object_storage.py
- cli/setup.py
- sdk/kamonohashi/op/object_storage.py
> Update click to the latest version

- sdk/kamonohashi/op/rest/api/preprocessing_api.py
> Follow the latest api spec

- web-api/platypus/platypus/Controllers/spa/RoleController.cs
#312 に関して、対応いたしました。
ロール編集で登録済みの名前で保存できないように修正しました。
> ロール編集に名前の重複チェックを追加

- web-api/platypus/platypus/Controllers/spa/GitController.cs
- web-api/platypus/platypus/Controllers/spa/RegistryController.cs
#323 に関して、対応いたしました。
前処理、ノートブック、推論で使用中のGit,レジストリが削除できないように修正しました。
> 前処理等で使用中のgit,レジストリが削除できないように修正

- web-api/platypus/platypus/Controllers/spa/AccountController.cs
- web-api/platypus/platypus/Controllers/spa/ClusterController.cs
- web-api/platypus/platypus/Controllers/spa/ResourceController.cs
- web-api/platypus/platypus/Controllers/spa/TenantController.cs
- web-api/platypus/platypus/Controllers/spa/UserController.cs
- web-pages/src/store/modules/node.js
- web-pages/src/views/system-setting/node/Edit.vue
#321 に関して、対応いたしました。
テナントの一覧を表示する際テナント表示名でソートして表示しなければ、ソートされていないように見えてしまいます。（多数の画面でテナント名は表示されないため）
ご確認をお願いします。
> テナント表示名でソートするように修正

- web-api/platypus/platypus/Controllers/spa/DataController.cs
#159 に関して対応いたしました。
データ編集画面で表示するファイルの表示順を名前順にするよう修正しました。
> データ編集画面で表示するファイルを名前順でソートするよう修正

- web-api/platypus/platypus/ApiModels/InferenceApiModels/InferenceDetailsOutputModel.cs
- web-api/platypus/platypus/ApiModels/NotebookApiModels/CreateInputModel.cs
- web-api/platypus/platypus/ApiModels/NotebookApiModels/DetailsOutputModel.cs
- web-api/platypus/platypus/ApiModels/NotebookApiModels/RerunInputModel.cs
- web-api/platypus/platypus/ApiModels/PreprocessingApiModels/CreateInputModel.cs
- web-api/platypus/platypus/ApiModels/PreprocessingApiModels/EditInputModel.cs
- web-api/platypus/platypus/ApiModels/PreprocessingApiModels/IndexOutputModel.cs
- web-api/platypus/platypus/ApiModels/PreprocessingApiModels/RunPreprocessHistoryInputModel.cs
- web-api/platypus/platypus/ApiModels/ResourceApiModels/ContainerDetailsForTenantOutputModel.cs
- web-api/platypus/platypus/ApiModels/TrainingApiModels/CreateInputModel.cs
- web-api/platypus/platypus/ApiModels/TrainingApiModels/DetailsOutputModel.cs
- web-api/platypus/platypus/Infrastructure/Infos/ContainerDetailsInfo.cs
- web-api/platypus/platypus/Models/TenantModels/InferenceHistory.cs
- web-api/platypus/platypus/Models/TenantModels/NotebookHistory.cs
- web-api/platypus/platypus/Models/TenantModels/Preprocess.cs
- web-api/platypus/platypus/Models/TenantModels/PreprocessHistory.cs
- web-api/platypus/platypus/Models/TenantModels/TrainingHistory.cs
- web-api/platypus/platypus/ServiceModels/ClusterManagementModels/RunContainerInputModel.cs
- web-api/platypus/platypus/Services/Interfaces/IClusterManagementService.cs
- web-api/platypus/platypus/Services/KubernetesService.cs
#342 について、対応いたしました。
画面側に合わせて、サーバ側のメモリの単位を`G`に統一しました。
コメント部もあわせて修正いたしました。
ご確認をお願いします。
> ジョブ作成時のメモリの単位が画面とサーバ側で異なるのを修正(GiB→G)

- sdk/sdk-genarator/README.md
- sdk/sdk-genarator/filter-sdk.py
- sdk/sdk-genarator/generate-sdk.sh
- sdk/sdk-genarator/rest.py.patch
> Add sdk generator

- web-api/platypus/platypus/Controllers/spa/ResourceController.cs
- web-api/platypus/platypus/DataAccess/Repositories/UserRepository.cs
- web-api/platypus/platypus/Services/KubernetesService.cs
- web-pages/src/views/system-setting/cluster-resource/ContainerList.vue
- web-pages/src/views/system-setting/cluster-resource/Node.vue
- web-pages/src/views/system-setting/cluster-resource/Tenant.vue
#403 
管理系コンテナがリソース量に計上されない問題を修正
> リソース利用状況画面の表示を修正

- web-api/platypus/platypus/Infrastructure/Types/GitServiceType.cs
- web-api/platypus/platypus/Logic/ClusterManagementLogic.cs
- web-api/platypus/platypus/Logic/GitLogic.cs
- web-api/platypus/platypus/Logic/Interfaces/IGitLogic.cs
- web-api/platypus/platypus/ServiceModels/Git/GitHubModels/GetUserModel.cs
- web-api/platypus/platypus/ServiceModels/Git/GitLabModels/GetUserModel.cs
- web-api/platypus/platypus/Services/GitBucketService.cs
- web-api/platypus/platypus/Services/GitHubService.cs
- web-api/platypus/platypus/Services/GitLabService.cs
- web-api/platypus/platypus/Services/Interfaces/IGitService.cs
- web-api/platypus/platypus/Services/PlatypusServiceBase.cs
- web-api/platypus/platypus/Startup.cs
gitbucketサポート
リポジトリ登録時に末尾に/があるとcloneできないバグの修正
> Feature gitbucket

- web-pages/src/components/selector/KqiGitSelector.vue
> コミットidを選択する際に、コミッター、コメントを表示するように変更

- release-tools/build-docker/web-pages-Dockerfile
- web-pages/package-lock.json
- web-pages/package.json
- node v12.20.1
- npm v6.14.10
> node,npm  verup対応

- web-pages-aquarium/src/views/dataSet/Detail.vue
- web-pages-aquarium/src/views/experiment/Detail/Index.vue
- web-pages-aquarium/src/views/modelTemplate/Detail/Index.vue
Reverts KAMONOHASHI/kamonohashi#514
user権限のみだとデータ作成ができないバグが見つかったため、差し戻します
> Revert "タブ切り替えやversion選択がある画面のURLにパラメタを追加するように修正issue#513"

- web-pages-aquarium/src/views/dataSet/Detail.vue
- web-pages-aquarium/src/views/experiment/Detail/Index.vue
- web-pages-aquarium/src/views/modelTemplate/Detail/Index.vue
Reverts KAMONOHASHI/kamonohashi#525
Revertを間違えたためRevertのRevert
> Revert "Revert "タブ切り替えやversion選択がある画面のURLにパラメタを追加するように修正issue#513""

- web-api/platypus/platypus/Controllers/spa/TenantController.cs
- web-api/platypus/platypus/Infrastructure/Options/ContainerManageOptions.cs
- web-api/platypus/platypus/Services/KubernetesService.cs
- web-api/platypus/platypus/appsettings.json
> namespace除外指定機能の追加

- web-pages-aquarium/src/views/experiment/Detail/Inference.vue
> 推論実行時の入力必須項目チェックでエラー時にダイアログがクローズしないように修正　issue#518

- web-pages/src/views/dataSet/DatasetTransfer/DataList.vue
- web-pages/src/views/dataSet/DatasetTransfer/Index.vue
Reverts KAMONOHASHI/kamonohashi#539
データ件数が多い（数万件）場合に問題があるので取り消し
> Revert "データセットのデータ選択画面で全データ選択チェックボックスをつけてデータの移動をした場合の挙動を修正 issue#120"

- web-pages/src/components/KqiPathInfo.vue
- web-pages/src/views/inference/Create.vue
- web-pages/src/views/notebook/Create.vue
- web-pages/src/views/training/Create.vue
データパスだけだと分かりにくいのでデータ名も表示するように修正
> 学習のコピー実行時にもデータセットのデータパス一覧を表示するように修正

- web-api/platypus/platypus/Logic/DataLogic.cs
> 4.0.1リリースのためのマージ

- web-pages-aquarium/src/components/selector/KqiResourceSelector.vue
- web-pages/src/components/selector/KqiResourceSelector.vue
リソース選択時のエラーメッセージの値の表示判定がおかしい点を修正
> リソース設定画面のエラーメッセージ表示の判定を修正

- cli/kamonohashi/cli/inference.py
- cli/kamonohashi/cli/training.py
- web-api/platypus/platypus/Services/ObjectStorageS3Service.cs
training, inferenceにlist-container-filesコマンドを追加
training, inferenceのdownload-container-filesコマンドに-fオプションを追加
minioの最近のバージョンでListObjectsV2Asyncの挙動が変化したことに対応
> ジョブ出力ファイルの扱いを強化した

- web-api/platypus/platypus/Controllers/spa/InferenceController.cs
> 推論履歴の検索時の件数取得の方法を変更
